version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_data
    volumes:
      - ./resources/db-seed.sql:/docker-entrypoint-initdb.d/db-seed.sql
  postgresAdmin:
    image: dpage/pgadmin4:latest
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=asdf@asdf.com
      - PGADMIN_DEFAULT_PASSWORD=asdf
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"
  app:
    build: .
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0"]
    ports:
      - "8000:8000"
    environment:
      POSTGRES_URL: "postgres"
      PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "app_data"
    volumes:
      - ./:/src/
